In [1]:
import numpy as np

Array and matrix are the 2 types of data-types majorly found in numpy. Matrices are also an array, they are subset of arrays.

In [5]:
np.array([1,2,4,'rinas',4+6j])

array(['1', '2', '4', 'rinas', '(4+6j)'], dtype='<U64')

In [6]:
# 1-D array
np.array([1,4,6,7.3,9.2])  

array([1. , 4. , 6. , 7.3, 9.2])

In [8]:
# 2-D array
np.array([[1,3],[5,7]])
# Imagine a 2-D co-ordinate system with co-ordinates --> (0,0) will have value 1, (0,1) have value 5, (1,0) has value 3 and (1,1) has value 7.

array([[1, 3],
       [5, 7]])

In [14]:
# We can enclose our data in list or even tuple, both give same results.
np.array([(1,3),(5,7)])

array([[1, 3],
       [5, 7]])

In [9]:
np.array([[1,3],[5,7],[4,6,3]])
# since no. of elements is different, it holds each one as a list.

<ipython-input-9-8297f8c20156>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[5,7],[4,6,3]])


array([list([1, 3]), list([5, 7]), list([4, 6, 3])], dtype=object)

In [10]:
# 3-D array
np.array([[[2,4],[6,7]],[[5,3],[9,1]]])

array([[[2, 4],
        [6, 7]],

       [[5, 3],
        [9, 1]]])

In [12]:
# 3-D array
np.array([2,4,6], ndmin = 3)

array([[[2, 4, 6]]])

In [13]:
# Type casting of data-type
np.array([43,6,7], dtype= complex)

array([43.+0.j,  6.+0.j,  7.+0.j])

In [ ]:
In numpy, there are variations of integer data-type like 8-bit, 16-bit, 32-bit, 64-bit, etc.
Inside an array, we can give different data-types to different elements inside the list.

In [21]:
# 'a' in dtype refers to first element in our list (3 & 4), while 'b' will refer to second element in the list (6 & 8).
arr = np.array([(3,6),(4,8)], dtype = [('a','<i1'), ('b','<i8')])

i2 notation stands for int16 bit and i8 stands for int64 bits. i1 -- int8 bits, i4 -- int32 bits, i16 doesnot exists in numpy.
- Default data type is int32 bit.

In [22]:
arr[0][0]

3

In [23]:
type(arr[0][0])

numpy.int8

In [24]:
type(arr[0][1])

numpy.int64

In [30]:
matt = np.mat(arr)

In [31]:
matt

matrix([[(3, 6), (4, 8)]], dtype=[('a', 'i1'), ('b', '<i8')])

In [26]:
l = [34,7,4,3,6,8,2]

In [27]:
np.array(l)

array([34,  7,  4,  3,  6,  8,  2])

In [28]:
np.asarray(l)

array([34,  7,  4,  3,  6,  8,  2])

In [29]:
np.asanyarray(l)

array([34,  7,  4,  3,  6,  8,  2])

#### Matrices are also an array, they are subset of arrays

In [ ]:
asanyarray() will not convert matrix into array, as matrix is also a sub-class of array.

In [32]:
np.asanyarray(matt)

matrix([[(3, 6), (4, 8)]], dtype=[('a', 'i1'), ('b', '<i8')])

In [33]:
np.array(matt)

array([[(3, 6), (4, 8)]], dtype=[('a', 'i1'), ('b', '<i8')])

In [35]:
# Check whether matrixes are sub-class of ndarray or not.
issubclass(np.matrix, np.ndarray)

True

#### ndarray stands for n-dimensional array.

In [36]:
# Check whether ndarray is sub-class of matrices.
issubclass(np.ndarray, np.matrix)

False

#### np.copy(): Copies all the data of the array at a new location.

In [37]:
arr = np.array([(3,6),(7,1)])

#### Shallow Copy

In [38]:
a = arr

#### Deep Copy

In [39]:
# b is pointing to the new location where all the arr data is copied.
b = np.copy(arr)

In [40]:
# Change value of array at 0,0 location.
arr[0][0] = 44

#### Arrays are mutable. We can change any data at a particular index.

In [41]:
arr

array([[44,  6],
       [ 7,  1]])

In [42]:
# a will have reassigned value
a

array([[44,  6],
       [ 7,  1]])

In [43]:
# b will hold old data. It will not reflect any subsequent changes that you make in original data after np.copy() operation.
b

array([[3, 6],
       [7, 1]])

Concepts of slicing and indexing applies on array elements as well.

In [45]:
arr[0:10]

array([[44,  6],
       [ 7,  1]])

In [46]:
arr[-1]

array([7, 1])

In [47]:
for i in arr:
    print(i)

[44  6]
[7 1]


In [49]:
# (4,4) gives dimensions of array. This lambda function coompares the row(i) & column(j) indexes and writes corr. result. 
#Diagonal having indexes 00, 11, 22, 33 will only return true
np.fromfunction(lambda i,j: i == j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [52]:
#i represents row index and j represents column index.
np.fromfunction(lambda i,j: i*j, (3,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [53]:
np.fromfunction(lambda i,j: i/j, (3,3))

<ipython-input-53-0411cf0e7457>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (3,3))
<ipython-input-53-0411cf0e7457>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In other languages or core python, 1/0 will give exceptions(0 division error) but `inf` is a keyword that exists within numpy.

In [64]:
gen = (i*i for i in range(5))

In [59]:
gen

<generator object <genexpr> at 0x000001769A7F60B0>

In [55]:
[i*i for i in range(5)]     # list comprehension

[0, 1, 4, 9, 16]

In [56]:
def test(v):
    yield v

In [57]:
test(5)

<generator object test at 0x000001769AA24740>

yield is a special type of keyword in python which will help to create a function whose behaviour is like generator.

In [60]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

As we have extracted the data from gen, the cursor is at last position. Now if we try to extract data we won't get it.

In [61]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

##### Convert string data to n-dim array.

In [67]:
np.fromstring('3,5,7,8,9,2', sep=',', dtype = int)

array([3, 5, 7, 8, 9, 2])

In [68]:
np.fromstring('34 53 766 3532', sep=' ', dtype = complex)

array([  34.+0.j,   53.+0.j,  766.+0.j, 3532.+0.j])

In [69]:
arr1 = np.array([[2,4,5,7],[4,3,6,7],[2,3,9,4]])

In [70]:
# Dimensions of array
arr1.ndim

2

In [71]:
# Total no. of elements
arr1.size

12

In [72]:
# Rows vs columns
arr1.shape

(3, 4)

In [73]:
arr2 = np.array([[[2,3,4,5],[5,6,7,8]],[[2,3,4,5],[5,6,7,8]]])

In [74]:
arr2

array([[[2, 3, 4, 5],
        [5, 6, 7, 8]],

       [[2, 3, 4, 5],
        [5, 6, 7, 8]]])

In [75]:
# We have 2 number of 2 cross 4 data. Hence shape is (2,2,4)
arr2.shape

(2, 2, 4)

### 4-dimension array

In [77]:
arr3 = np.array([[[[2,3,4,5],[5,6,7,8]],[[2,3,4,5],[5,6,7,8]], 
                 [[2,3,4,5],[5,6,7,8]],[[2,3,4,5],[5,6,7,8]]]])

In [78]:
arr3

array([[[[2, 3, 4, 5],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 6, 7, 8]],

        [[2, 3, 4, 5],
         [5, 6, 7, 8]]]])

In [79]:
arr3.ndim

4

Creation wise 4th dimension exists but visualisation wise it is difficult to visualise.

In [80]:
arr3.shape

(1, 4, 2, 4)

In [ ]:
we have 1 such object of 4 arrays of 2 cross 4 dimensions.

In [81]:
range(6.6)

TypeError: 'float' object cannot be interpreted as an integer

#### arange function in numpy is equivalent to range function in nature but accepts floating point number as well.

In [82]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [83]:
# we can even give end point and step size in floating point. 
np.arange(6.4, 9.8, .4)

array([6.4, 6.8, 7.2, 7.6, 8. , 8.4, 8.8, 9.2, 9.6])

In [84]:
np.arange(7.3, 3.5,-.4)

array([7.3, 6.9, 6.5, 6.1, 5.7, 5.3, 4.9, 4.5, 4.1, 3.7])

##### It includes upper bound as well for floating point numbers (not actually) but not for integers.

In [85]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

#### linspace(): Returns evenly spaced numbers over the specified interval.

In [86]:
# It generates data between 1 and 2 but at such intervals that total data is 5.
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# By default linspace gives us 50 number of datasets between any two numbers defined.

In [95]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [97]:
np.linspace(2,4,4,endpoint=False, axis=0) # axis=1 is possible only for more than 1 dim array.

array([2. , 2.5, 3. , 3.5])

In [100]:
np.linspace([1,2],[2,4],4,endpoint=True, axis=1)

array([[1.        , 1.33333333, 1.66666667, 2.        ],
       [2.        , 2.66666667, 3.33333333, 4.        ]])

In [103]:
np.linspace([1,5],3,5,endpoint=True, axis=1)
# 1 to 3 and 5 to 3 in 5 steps each.

array([[1. , 1.5, 2. , 2.5, 3. ],
       [5. , 4.5, 4. , 3.5, 3. ]])

In [87]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [89]:
np.zeros((2,4,5))   # 2 matrices of 4*5

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [90]:
np.zeros((2,3,3,1))

array([[[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]]])

In [91]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
np.ones((2,3,2)) + 6

array([[[7., 7.],
        [7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.],
        [7., 7.]]])

In [93]:
# Generates random data of given shape.
np.empty((3,4))

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### np.eye(n) creates identity matrices of n*n.

In [94]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### np.logspace(): Returns number spaced evenly on a log-scale.

In [104]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [107]:
# This is a 1-D data so transpose is not possible, but I want to change shape from 
d = np.linspace(2,4,30)

In [108]:
d

array([2.        , 2.06896552, 2.13793103, 2.20689655, 2.27586207,
       2.34482759, 2.4137931 , 2.48275862, 2.55172414, 2.62068966,
       2.68965517, 2.75862069, 2.82758621, 2.89655172, 2.96551724,
       3.03448276, 3.10344828, 3.17241379, 3.24137931, 3.31034483,
       3.37931034, 3.44827586, 3.51724138, 3.5862069 , 3.65517241,
       3.72413793, 3.79310345, 3.86206897, 3.93103448, 4.        ])

In [109]:
d.ndim

1

In [110]:
d.shape

(30,)

Let's change its shape from `1*30` to `30*1`

In [111]:
d.reshape(30,1)

array([[2.        ],
       [2.06896552],
       [2.13793103],
       [2.20689655],
       [2.27586207],
       [2.34482759],
       [2.4137931 ],
       [2.48275862],
       [2.55172414],
       [2.62068966],
       [2.68965517],
       [2.75862069],
       [2.82758621],
       [2.89655172],
       [2.96551724],
       [3.03448276],
       [3.10344828],
       [3.17241379],
       [3.24137931],
       [3.31034483],
       [3.37931034],
       [3.44827586],
       [3.51724138],
       [3.5862069 ],
       [3.65517241],
       [3.72413793],
       [3.79310345],
       [3.86206897],
       [3.93103448],
       [4.        ]])

In [112]:
#We can even reshape the data in 3-dimensions.
d.reshape(1,2,15)  # make sure the dimension is satisfied to number of data.

array([[[2.        , 2.06896552, 2.13793103, 2.20689655, 2.27586207,
         2.34482759, 2.4137931 , 2.48275862, 2.55172414, 2.62068966,
         2.68965517, 2.75862069, 2.82758621, 2.89655172, 2.96551724],
        [3.03448276, 3.10344828, 3.17241379, 3.24137931, 3.31034483,
         3.37931034, 3.44827586, 3.51724138, 3.5862069 , 3.65517241,
         3.72413793, 3.79310345, 3.86206897, 3.93103448, 4.        ]]])

In [114]:
np.random.rand(3)   # distributes data based on uniform dist b/w 0 to 1.

array([0.19056882, 0.33352837, 0.2043469 ])

In [115]:
np.random.randn(3)   # distributes data based on std. normal distribution with mean=0, sd=1

array([-0.86848993, -1.35304655, -1.68372347])

In [116]:
# Generates random integer b/w given bound.
np.random.randint(6)

4

In [117]:
np.random.randint(45,56)

47

In [118]:
# Genrates a 3*4 matrix with values b/w 45 to 56.
np.random.randint(45,56,(3,4))

array([[51, 54, 45, 50],
       [53, 55, 50, 54],
       [48, 46, 51, 53]])

In [2]:
arr = np.random.randint(4,7,(3,4))

In [3]:
arr

array([[6, 5, 4, 6],
       [4, 4, 5, 6],
       [5, 6, 5, 6]])

In [121]:
arr.reshape(2,6)

array([[6, 4, 5, 5, 4, 6],
       [5, 4, 4, 5, 6, 6]])

In [122]:
arr.reshape(2,3,2)

array([[[6, 4],
        [5, 5],
        [4, 6]],

       [[5, 4],
        [4, 5],
        [6, 6]]])

In [123]:
arr.reshape(4, -4435345)  # it automatically assumes the remaining column dim even though you give any negative number.

array([[6, 4, 5],
       [5, 4, 6],
       [5, 4, 4],
       [5, 6, 6]])

In [125]:
arr.reshape(1, -75845)  # here it assumes column = 12.

array([[6, 4, 5, 5, 4, 6, 5, 4, 4, 5, 6, 6]])

In [14]:
arr

array([[6, 5, 4, 6],
       [4, 4, 5, 6],
       [5, 6, 5, 6]])

In [15]:
arr.max()

6

In [16]:
arr.min()

4

In [18]:
arr = np.random.randint(10,200,(5,5))
arr

array([[139,  89,  38, 159,  45],
       [ 56, 142,  40,  83,  77],
       [ 70,  68, 141,  55,  18],
       [ 80,  85,  33, 198,  11],
       [ 24,  42, 168,  64,  29]])

In [19]:
# I want right hand bottom square elements 198,11,64,29.
arr[3:,3:]

array([[198,  11],
       [ 64,  29]])

In [20]:
# I want 1st and 3rd columns
arr[:,[1,3]]

array([[ 89, 159],
       [142,  83],
       [ 68,  55],
       [ 85, 198],
       [ 42,  64]])

In [21]:
#Filter all the data from array which is greater than 50.
arr[arr>50]

array([139,  89, 159,  56, 142,  83,  77,  70,  68, 141,  55,  80,  85,
       198, 168,  64])

In [22]:
arr1 = np.random.randint(2,5,(3,3))
arr2 = np.random.randint(2,5,(3,3))

In [23]:
arr1

array([[3, 3, 4],
       [4, 2, 4],
       [2, 2, 3]])

In [24]:
arr2

array([[2, 3, 3],
       [3, 3, 4],
       [2, 2, 4]])

In [25]:
# Element-wise direct multiplication not a matrix multiplication
arr1*arr2

array([[ 6,  9, 12],
       [12,  6, 16],
       [ 4,  4, 12]])

##### Matrix Multiplication

For matrix multiplication the no. of columns of first matrix should be equal to no. of rows of second matrix.

In [26]:
arr1 @ arr2

array([[23, 26, 37],
       [22, 26, 36],
       [16, 18, 26]])

#### Broadcasting

In [29]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
b = np.array([2,3,4,7])
b

array([2, 3, 4, 7])

In [ ]:
We have inserted b row wise in a.

In [31]:
a + b

array([[2., 3., 4., 7.],
       [2., 3., 4., 7.],
       [2., 3., 4., 7.]])

We have to perform column wise broadcasting. Then take a 1*3 matrix and take transpose. 

In [32]:
c = np.array([4,5,6])

Since, it is 1-D we cannot transpose. For doing a transpose operation we require 2-D array.

In [33]:
c.reshape(3,1) + a

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [34]:
arr = np.random.rand(5,4)

In [35]:
arr

array([[0.36518133, 0.3887994 , 0.18517263, 0.81835382],
       [0.88549974, 0.83060276, 0.58303653, 0.74644729],
       [0.48750362, 0.3116765 , 0.66951741, 0.35016239],
       [0.0499149 , 0.54651596, 0.35983074, 0.84395725],
       [0.61272093, 0.84685458, 0.18631543, 0.21174452]])

In [36]:
# Square-root of all elements of given array
np.sqrt(arr)

array([[0.60430235, 0.62353781, 0.43031689, 0.9046291 ],
       [0.94100996, 0.9113741 , 0.76356829, 0.86397181],
       [0.6982146 , 0.55827995, 0.81824043, 0.59174521],
       [0.22341643, 0.73926717, 0.59985894, 0.91867146],
       [0.78276492, 0.92024702, 0.43164271, 0.46015706]])

In [37]:
np.exp(arr)

array([[1.44077524, 1.47520859, 1.20342617, 2.26676525],
       [2.42419556, 2.29470147, 1.79147004, 2.10949227],
       [1.62824642, 1.36571281, 1.95329445, 1.41929801],
       [1.05118164, 1.7272248 , 1.43308684, 2.32555158],
       [1.8454459 , 2.33229925, 1.20480223, 1.23583211]])

In [38]:
# We can find log base=2,10,e
np.log10(arr)

array([[-0.43749144, -0.41027442, -0.73242321, -0.08705889],
       [-0.05281156, -0.08060663, -0.23430423, -0.12700085],
       [-0.31202215, -0.50629595, -0.17423813, -0.4557305 ],
       [-1.3017698 , -0.26239715, -0.44390173, -0.07367955],
       [-0.21273729, -0.07219116, -0.72975118, -0.67418783]])

##### seed()

In [41]:
# After running seed(any_number), the array we run having random numbers will get fixed & not change on subsequent executions.
np.random.seed(44)
np.random.rand(2,5)

array([[0.83484215, 0.1047961 , 0.74464048, 0.36050084, 0.35931084],
       [0.60923838, 0.39377955, 0.40907261, 0.50990241, 0.71014799]])

### Merging two jupyter notebooks

In [42]:
!pip install nbmerge

In [48]:
!nbmerge Pandas_2.ipynb pandas_new.ipynb -o pandas_3.ipynb